spring.application.name=Accounts

server.port=8082

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=CREDITCARD
spring.datasource.password=Credit@123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=true
spring.jpa.properties.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.format_sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never